// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\Ruslan\GolandProjects\request-service\internal\domain\service\request\dependency.go

// Package test is a generated GoMock package.
package test

import (
	model "RequestService/internal/domain/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockrequestRepository is a mock of requestRepository interface.
type MockrequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockrequestRepositoryMockRecorder
}

// MockrequestRepositoryMockRecorder is the mock recorder for MockrequestRepository.
type MockrequestRepositoryMockRecorder struct {
	mock *MockrequestRepository
}

// NewMockrequestRepository creates a new mock instance.
func NewMockrequestRepository(ctrl *gomock.Controller) *MockrequestRepository {
	mock := &MockrequestRepository{ctrl: ctrl}
	mock.recorder = &MockrequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrequestRepository) EXPECT() *MockrequestRepositoryMockRecorder {
	return m.recorder
}

// CreateRequest mocks base method.
func (m *MockrequestRepository) CreateRequest(ctx context.Context, request model.Request, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRequest", ctx, request, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRequest indicates an expected call of CreateRequest.
func (mr *MockrequestRepositoryMockRecorder) CreateRequest(ctx, request, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRequest", reflect.TypeOf((*MockrequestRepository)(nil).CreateRequest), ctx, request, userID)
}

// GetHandlingRequests mocks base method.
func (m *MockrequestRepository) GetHandlingRequestsWithLock(ctx context.Context, userID int64) (model.Requests, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHandlingRequestsWithLock", ctx, userID)
	ret0, _ := ret[0].(model.Requests)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHandlingRequests indicates an expected call of GetHandlingRequests.
func (mr *MockrequestRepositoryMockRecorder) GetHandlingRequests(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandlingRequestsWithLock", reflect.TypeOf((*MockrequestRepository)(nil).GetHandlingRequestsWithLock), ctx, userID)
}

// GetRequest mocks base method.
func (m *MockrequestRepository) GetRequest(ctx context.Context, id int64) (model.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequest", ctx, id)
	ret0, _ := ret[0].(model.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequest indicates an expected call of GetRequest.
func (mr *MockrequestRepositoryMockRecorder) GetRequest(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequest", reflect.TypeOf((*MockrequestRepository)(nil).GetRequest), ctx, id)
}
